#!/usr/bin/env python3
"""Generate docs/julia-api.md from the DataManifest.jl repo's docs/api.md.

Usage: python docs/_sync_julia_api.py <path-to-DataManifest.jl>/docs/api.md

The adaptation is mechanical:
- a note is inserted after the page title, pointing at the source of truth;
- relative links to other pages of the Julia docs site (doc.md, storage.md,
  caching.md, language-bindings.md, ...) are rewritten to absolute URLs under
  https://awi-esc.github.io/DataManifest.jl/ in mkdocs URL style
  (doc.md -> /doc/, anchors preserved);
- in-page anchor links (#database, ...) are left untouched.

The output is written next to this script as julia-api.md.
"""

import re
import sys
from pathlib import Path

JULIA_SITE = "https://awi-esc.github.io/DataManifest.jl/"

# The page set of the Julia docs site, per its mkdocs.yml nav.
JULIA_PAGES = {
    "index",
    "installation",
    "quickstart",
    "doc",
    "caching",
    "language-bindings",
    "storage",
    "configuration",
    "shell",
    "api",
}

NOTE = (
    "<!-- Generated by docs/_sync_julia_api.py — do not edit by hand. -->\n"
    "\n"
    "!!! note\n"
    "    This page mirrors the DataManifest.jl API reference; the source of\n"
    "    truth lives in the\n"
    "    [DataManifest.jl repository](https://github.com/awi-esc/DataManifest.jl/blob/main/docs/api.md).\n"
    "    It is regenerated from that repository on every deploy of this site.\n"
)

LINK_RE = re.compile(r"\(([a-z0-9-]+)\.md(#[^)]*)?\)")


def rewrite_link(match: re.Match) -> str:
    page, anchor = match.group(1), match.group(2) or ""
    if page not in JULIA_PAGES:
        print(f"warning: unknown Julia docs page {page!r}, link left as-is",
              file=sys.stderr)
        return match.group(0)
    url = JULIA_SITE if page == "index" else f"{JULIA_SITE}{page}/"
    return f"({url}{anchor})"


def adapt(source: str) -> str:
    text = LINK_RE.sub(rewrite_link, source)
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("# "):
            lines.insert(i + 1, "\n" + NOTE)
            break
    else:
        lines.insert(0, NOTE + "\n")
    return "".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <path-to-DataManifest.jl-docs-api.md>")
    source = Path(sys.argv[1]).read_text(encoding="utf-8")
    out_path = Path(__file__).resolve().parent / "julia-api.md"
    out_path.write_text(adapt(source), encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
