#!/usr/bin/env python3
"""Generate docs/manifest-spec.md from the datamanifest.toml repo's SCHEMA.md.

Usage: python docs/_sync_spec.py <path-to-datamanifest.toml>/SCHEMA.md

The adaptation is mechanical:
- a note is inserted after the page title, pointing at the source of truth;
- relative links inside SCHEMA.md (currently there are none) are rewritten to
  GitHub blob URLs under the spec repository
  (https://github.com/perrette/datamanifest.toml/blob/main/<file>, anchors
  preserved);
- absolute (http/https) links and in-page anchor links (#versioning, ...) are
  left untouched.

The output is written next to this script as manifest-spec.md.
"""

import re
import sys
from pathlib import Path

SPEC_BLOB = "https://github.com/perrette/datamanifest.toml/blob/main"

NOTE = (
    "<!-- Generated by docs/_sync_spec.py — do not edit by hand. -->\n"
    "\n"
    "!!! note\n"
    "    This page mirrors the normative specification; the source of truth\n"
    "    is\n"
    "    [SCHEMA.md in the datamanifest.toml repository](https://github.com/perrette/datamanifest.toml/blob/main/SCHEMA.md).\n"
    "    It is regenerated from that repository on every deploy of this site.\n"
)

# An inline link whose target is neither an absolute URL (scheme:) nor an
# in-page anchor (#...): a path relative to the spec repository root.
LINK_RE = re.compile(r"\]\((?![a-z][a-z0-9+.-]*:|#)([^)#\s]+)(#[^)]*)?\)")


def rewrite_link(match: re.Match) -> str:
    path, anchor = match.group(1), match.group(2) or ""
    while path.startswith("./"):
        path = path[2:]
    return f"]({SPEC_BLOB}/{path}{anchor})"


def adapt(source: str) -> str:
    text = LINK_RE.sub(rewrite_link, source)
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("# "):
            lines.insert(i + 1, "\n" + NOTE)
            break
    else:
        lines.insert(0, NOTE + "\n")
    return "".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <path-to-datamanifest.toml-SCHEMA.md>")
    source = Path(sys.argv[1]).read_text(encoding="utf-8")
    out_path = Path(__file__).resolve().parent / "manifest-spec.md"
    out_path.write_text(adapt(source), encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
